name: Auto-approve Dependabot PRs

on:
  workflow_dispatch:

jobs:
  approve-dependabot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Approve All Dependabot PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Fetching all open pull requests...');
            
            // Fetch all open PRs
            const { data: openPRs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            
            console.log(`Found ${openPRs.length} open PR(s)`);
            
            // Filter for Dependabot PRs
            const dependabotPRs = openPRs.filter(pr => 
              pr.user.login === 'dependabot[bot]' || pr.user.login === 'dependabot-preview[bot]'
            );
            
            console.log(`Found ${dependabotPRs.length} Dependabot PR(s)`);
            
            if (dependabotPRs.length === 0) {
              console.log('No Dependabot PRs to approve');
              return;
            }
            
            // Process each Dependabot PR
            for (const pr of dependabotPRs) {
              try {
                console.log(`\nProcessing PR #${pr.number}: ${pr.title}`);
                
                // Check existing reviews
                const { data: reviews } = await github.rest.pulls.listReviews({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                });
                
                const hasApproval = reviews.some(review => 
                  review.state === 'APPROVED'
                );
                
                if (!hasApproval) {
                  await github.rest.pulls.createReview({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    event: 'APPROVE',
                    body: '🤖 Auto-approved by GitHub Actions'
                  });
                  console.log(`✅ Approved PR #${pr.number}`);
                } else {
                  console.log(`ℹ️ PR #${pr.number} already has an approval`);
                }
              } catch (error) {
                console.error(`❌ Error processing PR #${pr.number}: ${error.message}`);
              }
            }
            
            console.log(`\n✨ Finished processing ${dependabotPRs.length} Dependabot PR(s)`);
